config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :weapons

  resources :robots

  resources :code_names

  root "welcome#index"

end

app/models/code_name.rb
class CodeName < ActiveRecord::Base
    has_many :robots

    validates :name, length: { minimum: 3 }#, message: "It has to be at least 3 characters long"
    validates :name, uniqueness: true#, message: "should happen once per year"

    validates :info_reference, length: { minimum: 3 }#, message: "It has to be at least 3 characters long"
    validates :info_reference, format: { with: /wiki/ }#, message: "It has to have a wiki reference"

    validates :damage, numericality: { greater_than: 0 }

end

app/controllers/code_names_controller.rb
class CodeNamesController < ApplicationController
  before_action :set_code_name, only: [:show, :edit, :update, :destroy]

  # GET /code_names
  # GET /code_names.json
  def index
    @code_names = CodeName.all
  end

  # GET /code_names/1
  # GET /code_names/1.json
  def show
  end

  # GET /code_names/new
  def new
    @code_name = CodeName.new
  end

  # GET /code_names/1/edit
  def edit
  end

  # POST /code_names
  # POST /code_names.json
  def create
    @code_name = CodeName.new(code_name_params)

    respond_to do |format|
      if @code_name.save
        format.html { redirect_to code_names_path, notice: 'Code name was successfully created.' }
        format.json { render :show, status: :created, location: @code_name }
      else
        format.html { render :new }
        format.json { render json: @code_name.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /code_names/1
  # PATCH/PUT /code_names/1.json
  def update
    respond_to do |format|
      if @code_name.update(code_name_params)
        format.html { redirect_to @code_name, notice: 'Code name was successfully updated.' }
        format.json { render :show, status: :ok, location: @code_name }
      else
        format.html { render :edit }
        format.json { render json: @code_name.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /code_names/1
  # DELETE /code_names/1.json
  def destroy
    @code_name.destroy
    respond_to do |format|
      format.html { redirect_to code_names_url, notice: 'Code name was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_code_name
      @code_name = CodeName.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def code_name_params
      params.require(:code_name).permit(:name, :info_reference, :damage)
    end
end

app/helpers/code_names_helper.rb
module CodeNamesHelper
end

app/views/code_names/_form.html.erb
<%= form_for(@code_name) do |f| %>
  <% if @code_name.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@code_name.errors.count, "error") %> prohibited this code_name from being saved:</h2>

      <ul>
      <% @code_name.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :info_reference %><br>
    <%= f.text_field :info_reference %>
  </div>
  <div class="field">
    <%= f.label :damage %><br>
    <%= f.number_field :damage %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/code_names/edit.html.erb
<h1>Editing code_name</h1>

<%= render 'form' %>

<%= link_to 'Show', @code_name %> |
<%= link_to 'Back', code_names_path %>

app/views/code_names/index.html.erb
<h1>Listing code_names</h1>

<table class="table-bordered table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Info reference</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @code_names.each do |code_name| %>
      <tr>
        <td><%= code_name.name %></td>
        <td><%= code_name.info_reference %></td>
        <td><%= link_to 'Show', code_name %></td>
        <td><%= link_to 'Edit', edit_code_name_path(code_name) %></td>
        <td><%= link_to 'Destroy', code_name, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Code name', new_code_name_path %>

app/views/code_names/new.html.erb
<h1>New code_name</h1>

<%= render 'form' %>

<%= link_to 'Back', code_names_path %>

app/views/code_names/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @code_name.name %>
</p>

<p>
  <strong>Info reference:</strong>
  <%= @code_name.info_reference %>
</p>

<%= link_to 'Edit', edit_code_name_path(@code_name) %> |
<%= link_to 'Back', code_names_path %>