config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :weapons

  resources :robots

  resources :code_names

  root "welcome#index"

end

app/models/robot.rb
class Robot < ActiveRecord::Base
  include AutoPresentable

  belongs_to :code_name

  has_many :robot_weapons
  has_many :weapons, through: :robot_weapons

  has_one :health, as: :machine

  validates :code_name, presence: true #, message: "Needs to be a registered robot"
  validates :health, presence: true #, message: "Needs to be initialized with a health status"

  accepts_nested_attributes_for :health
  accepts_nested_attributes_for :robot_weapons
  accepts_nested_attributes_for :code_name

  delegate :damage, to: :code_name
  delegate :name, to: :code_name

  attr_accessor :is_frozen, :used_freeze

  after_initialize :check_attrs

  def check_attrs
    self.is_frozen = false
    self.used_freeze = false
  end

  def used_freeze?
    value = self.used_freeze
    self.used_freeze = false
    value
  end

  def is_frozen?
    value = self.is_frozen
    self.is_frozen = false
    value
  end

  def alive?
    remaining_health > 0
  end

  def remaining_health
    self.health.current
  end

  def take_damage damage
    # should not get lower than 0
    self.health.current -= damage
  end

  def calculate_damage(total_health=1)

    # No hace daño si esta congelado
    if self.is_frozen?
      return 0
    end

    # El daño que haga debe ser tal que no sobrepase por mucho el total_health (1)
    stable_weapons = robot_weapons.to_a.delete_if{ |weapon| !weapon.stable? }
    stable_weapons = stable_weapons.map{ |weapon| weapon.weapon } # Para que funcione obtener el daño con el key :damage
    stable_weapons << Weapon.new(damage: self.damage) # Para que entre en el calculo el daño del robot

    # Combinacion de armas que cumple (1)
    best = Optimization.optimize(stable_weapons, :damage, total_health).first

    # Si el arma congela, indicarlo
    if best.can_freeze?
      self.used_freeze = true
    end

    best[:damage]
  end

  def valid_and_heavier_weapon?(max_damage, weapon_instance)
    weapon_instance.stable? and max_damage < weapon_instance.damage
  end

  # pending test - then change it to work with an array instead of a hash
  def get_instance_state_message
    @status ||= 0
    @status %= 4
    {
        "0" => "H",
        "1" => "O",
        "2" => "L",
        "3" => "A"
    }[ ((@status+=1)-1).to_s ]
  end

end

app/controllers/robots_controller.rb
class RobotsController < ApplicationController
  before_action :set_robot, only: [:show, :edit, :update, :destroy]

  # GET /robots
  # GET /robots.json
  def index
    @robots = Robot.all
  end

  # GET /robots/1
  # GET /robots/1.json
  def show
  end

  # GET /robots/new
  def new
    @robot = Robot.new()
    @robot.health = Health.new
    @robot.code_name = CodeName.new
  end

  # GET /robots/1/edit
  def edit
  end

  # POST /robots
  # POST /robots.json
  def create

    if robot_params[:code_name_attributes][:id].present?
      h = robot_params.to_h
      id = robot_params[:code_name_attributes][:id]
      h.delete('code_name_attributes')
      @robot = Robot.new(h)
      @robot.code_name = CodeName.find(id)
    else
      @robot = Robot.new(robot_params)
    end

    respond_to do |format|
      if @robot.save
        format.html { redirect_to @robot, notice: 'Robot was successfully created.' }
        format.json { render :show, status: :created, location: @robot }
      else
        @robot.health = Health.new unless @robot.health
        format.html { render :new }
        format.json { render json: @robot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /robots/1
  # PATCH/PUT /robots/1.json
  def update
    respond_to do |format|
      if @robot.update(robot_params)
        format.html { redirect_to @robot, notice: 'Robot was successfully updated.' }
        format.json { render :show, status: :ok, location: @robot }
      else
        format.html { render :edit }
        format.json { render json: @robot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /robots/1
  # DELETE /robots/1.json
  def destroy
    @robot.destroy
    respond_to do |format|
      format.html { redirect_to robots_url, notice: 'Robot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_robot
      @robot = Robot.find(params[:id])
      @robot.health = Health.new unless @robot.health
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def robot_params
      params.require(:robot).permit(:code_name_attributes => [:info_reference, :name, :damage, :id], :health_attributes => [:current, :maximum])
    end
end

app/helpers/robots_helper.rb
module RobotsHelper
end

app/views/robots/_form.html.erb
<%= nested_form_for(@robot) do |f| %>
    <% if @robot.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@robot.errors.count, "error") %> prohibited this robot from being saved:</h2>

          <ul>
            <% @robot.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    Select a code name...

    Or create a new one:

    <%= render "application/shared/code_name_form", f: f %>

   <%= render "application/shared/health_form", f: f %>

    <%= f.fields_for :robot_weapons do |robot_weapon_form| %>
        <%= render "application/shared/robot_weapon_form", f: robot_weapon_form %>
    <% end %>
    <p><%= f.link_to_add "Add a Weapon", :robot_weapons %></p>


    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/robots/edit.html.erb
<h1>Editing robot</h1>

<%= render 'form' %>

<%= link_to 'Show', @robot %> |
<%= link_to 'Back', robots_path %>

app/views/robots/index.html.erb
<h1>Listing robots</h1>

<table class="table-bordered table-striped table-hover">
  <thead>
    <tr>
      <th>Code name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @robots.each do |robot| %>
      <tr>
        <td><%= robot.code_name_id %></td>
        <td><%= link_to 'Show', robot %></td>
        <td><%= link_to 'Edit', edit_robot_path(robot) %></td>
        <td><%= link_to 'Destroy', robot, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Robot', new_robot_path %>

app/views/robots/new.html.erb
<h1>New robot</h1>

<%= render 'form' %>

<%= link_to 'Back', robots_path %>

app/views/robots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code name:</strong>
  <%= @robot.code_name_id %>
</p>

<%= link_to 'Edit', edit_robot_path(@robot) %> |
<%= link_to 'Back', robots_path %>