config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :weapons

  resources :robots

  resources :code_names

  root "welcome#index"

end

app/models/weapon.rb
class Weapon < ActiveRecord::Base
  has_many :robot_weapons
  has_many :robots, through: :robot_weapons

  #validates_uniqueness_of :name

  # if created with the same name as one previously saved should return that one

  # validates :name, uniqueness: true
  # validate :get_instance_by_name

  def get_instance_by_name
    # return the existing object if any, otherwise return true
  end

  def can_freeze?
    can_freeze
  end

  def create_or_update

    if self.name.present?

      weapon = Weapon.find_by(name: self.name)

      if weapon.present?

        if new_record?
          self.id = weapon.id
          self.created_at = weapon.created_at
          result = update_record
          return result != false
        else
          self.id = weapon.id
          changed_attributes.delete(:id)
        end

      end

    end

    super
  end

end

app/controllers/weapons_controller.rb
class WeaponsController < ApplicationController
  before_action :set_weapon, only: [:show, :edit, :update, :destroy]

  # GET /weapons
  # GET /weapons.json
  def index
    @weapons = Weapon.all
  end

  # GET /weapons/1
  # GET /weapons/1.json
  def show
  end

  # GET /weapons/new
  def new
    @weapon = Weapon.new
  end

  # GET /weapons/1/edit
  def edit
  end

  # POST /weapons
  # POST /weapons.json
  def create
    @weapon = Weapon.new(weapon_params)

    respond_to do |format|
      if @weapon.save
        format.html { redirect_to @weapon, notice: 'Weapon was successfully created.' }
        format.json { render :show, status: :created, location: @weapon }
      else
        format.html { render :new }
        format.json { render json: @weapon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /weapons/1
  # PATCH/PUT /weapons/1.json
  def update
    respond_to do |format|
      if @weapon.update(weapon_params)
        format.html { redirect_to @weapon, notice: 'Weapon was successfully updated.' }
        format.json { render :show, status: :ok, location: @weapon }
      else
        format.html { render :edit }
        format.json { render json: @weapon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /weapons/1
  # DELETE /weapons/1.json
  def destroy
    @weapon.destroy
    respond_to do |format|
      format.html { redirect_to weapons_url, notice: 'Weapon was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_weapon
      @weapon = Weapon.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def weapon_params
      params.require(:weapon).permit(:name, :damage)
    end
end

app/helpers/weapons_helper.rb
module WeaponsHelper
end

app/views/weapons/_form.html.erb
<%= form_for(@weapon) do |f| %>
  <% if @weapon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@weapon.errors.count, "error") %> prohibited this weapon from being saved:</h2>

      <ul>
      <% @weapon.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :damage %><br>
    <%= f.number_field :damage %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/weapons/edit.html.erb
<h1>Editing weapon</h1>

<%= render 'form' %>

<%= link_to 'Show', @weapon %> |
<%= link_to 'Back', weapons_path %>

app/views/weapons/index.html.erb
<h1>Listing weapons</h1>

<table class="table-bordered table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Damage</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @weapons.each do |weapon| %>
      <tr>
        <td><%= weapon.name %></td>
        <td><%= weapon.damage %></td>
        <td><%= link_to 'Show', weapon %></td>
        <td><%= link_to 'Edit', edit_weapon_path(weapon) %></td>
        <td><%= link_to 'Destroy', weapon, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Weapon', new_weapon_path %>

app/views/weapons/new.html.erb
<h1>New weapon</h1>

<%= render 'form' %>

<%= link_to 'Back', weapons_path %>

app/views/weapons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @weapon.name %>
</p>

<p>
  <strong>Damage:</strong>
  <%= @weapon.damage %>
</p>

<%= link_to 'Edit', edit_weapon_path(@weapon) %> |
<%= link_to 'Back', weapons_path %>